coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%

comment:
  layout: "condensed_header, condensed_files"
  require_changes: true
